name: Build

on:
  push:
    branches:
      - main
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt install -y build-essential cmake libpipewire-0.3-dev libdbus-1-dev libportal-dev libavcodec-dev libavformat-dev
      - name: Generate Build Script
        working-directory: ${{ github.workspace }}/
        run: |
          cmake -B build
      - name: Build
        working-directory: ${{ github.workspace }}/
        run: |
          cmake --build build --config Release
