name: Build

on:
  push:
    branches:
      - main
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 1
      - name: Install Dependencies
        run: |
          sudo apt install -y build-essential cmake libpipewire-0.3-dev libdbus-1-dev libportal-dev libavcodec-dev libavformat-dev libswscale-dev libswresample-dev
      - name: Generate Build Script
        run: |
          cmake -B build
      - name: Build
        run: |
          cmake --build build --config Release
